name: CI
permissions:
  contents: read
  pull-requests: write

on: [push, pull_request]

jobs:
  lint_and_test:
    runs-on: ${{matrix.os}}
    strategy:
      max-parallel: 4
      matrix:
#        os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.11", "3.12", "3.13"]
    steps:
    - name: Git config
      run: git config --global core.autocrlf input
    - uses: actions/checkout@v6
    - name: Install system dependencies - ${{runner.os}}
      if: runner.os == 'Windows'
      run: |
        sed -i '/disable=/a \    no-member,' setup.cfg
    - name: Set up Python v${{matrix.python-version}} - ${{runner.os}}
      uses: actions/setup-python@v6
      with:
        python-version: ${{matrix.python-version}}
        cache: pip
    - name: Display Python version
      run: python --version
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip flit_core
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    - name: Lint (pylint)
      run: pylint myWhoosh2Garmin.py
    - name: Lint (ruff)
      run: ruff check myWhoosh2Garmin.py
    - name: Check types (mypy)
      run: mypy myWhoosh2Garmin.py
    - name: Check spelling (codespell)
      run: codespell README.md myWhoosh2Garmin.py
